services:
  db:
    build:
      context: .
      args:
        PG_IMAGE_VERSION: ${PG_IMAGE_VERSION}
        PG_GID: ${PG_GID}
        PG_UID: ${PG_UID}
    # OSの起動時にコンテナを起動
    restart: always
    volumes:
      # DBの永続化
      - db-volume:/var/lib/postgresql/data/
      # 設定ファイル
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      # 初期設定スクリプトファイル
      - ./initdb.d:/docker-entrypoint-initdb.d
    # 読み込む設定ファイル指定
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    # ポート指定
    ports:
      - "${PG_PORT}:5432"
    environment:
      # デフォルトDB名
      POSTGRES_DB: ${POSTGRES_DB}
      # デフォルトDBログインユーザー
      POSTGRES_USER: ${POSTGRES_USER}
      # デフォルトDBログインパスワード
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # タイムゾーン
      TZ: ${TZ}

# ボリューム設定（永続化のため）
volumes:
  db-volume:
    name: postgres-data
    driver: local